#!/bin/sh
#
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# UDEV script that sets up the debug link.

DEVICE_IP="169.254.100.2"
MAX_VETH_SUFFIX=99

devdir=""
for d in /sys/bus/usb/devices/*; do
  idVendor=$(cat "${d}/idVendor")
  idProduct=$(cat "${d}/idProduct")
  if [ "${idVendor}" = "0b95" -a "${idProduct}" = "7e2b" ]; then
    devdir="${d}"
  fi
done

if [ -z "${devdir}" ]; then
  logger "setup-debug-link: could not find debug link hardware"
  exit 1
fi

netdir=$(find "${devdir}/" -name "net")
ifname=$(ls "${netdir}")
address=$(cat "${netdir}/${ifname}/address")

ip link set dev "${ifname}" down

new_ifname=""
for i in $(seq 0 $MAX_VETH_SUFFIX); do
  new_ifname="veth${i}"
  nameif "${new_ifname}" "${address}"
  if [ $? -eq 0 ]; then
    break
  elif [ ${i} -eq $MAX_VETH_SUFFIX ]; then
    ip link set dev "${ifname}" up
    logger "setup-debug-link: could not find a veth* interface name"
    exit 1
  fi
done

ip address add "${DEVICE_IP}/24" dev "${new_ifname}"
ip link set dev "${new_ifname}" up
