# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

all:
	echo "Scripts only.  Nothing to make."

install:
	install -D modem-common.sh $(DESTDIR)/usr/lib/modem-common.sh
	install -D connectivity-common.sh $(DESTDIR)/usr/lib/connectivity-common.sh

	install -D modem $(DESTDIR)/usr/bin/modem
	install -D connectivity $(DESTDIR)/usr/bin/connectivity
