#!/bin/sh
# Copyright 2015 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This is a dummy implemenation for job-filter.conf.
#
# When starting Upstart jobs, "job-filter" will be invoked with job name as $1.
# System that wants to monitor jobs can override the filter by:
#  mount --bind MYFILTER /usr/sbin/job-filter
#
# A typical filter is to inhibit specific services, for example:
#  if [ "$1" = "powerd" ]; then stop -n powerd; fi
