#!/bin/sh
# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

getfield() {
  shift $1
  echo $1
}

EVENT=$1
shift
if [ $# -eq 0 ]; then
  set -- time
fi

while [ $# -gt 0 ]; do
  case "$1" in
    time)
      TAG=uptime
      FIELD=1
    ;;
    read-sectors)
      TAG=disk
      FIELD=3
    ;;
    write-sectors)
      TAG=disk
      FIELD=7
    ;;
    *)
      shift
      continue
    ;;
  esac
  # The 'boot-complete' upstart job tests for whether an event has
  # been recorded by calling this script, so it's not an error if
  # the requested event doesn't exist.
  EVENTFILE="/tmp/${TAG}-${EVENT}"
  if [ -f "$EVENTFILE" ]; then
    getfield $FIELD $(tail -1 "$EVENTFILE")
  fi
  shift
done
