#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

logger -t powerd_suspend "Going to suspend-to-RAM state"

# - logs the time going to suspend (no-op if no RTC).
cp /sys/class/rtc/rtc0/since_epoch /var/log/metrics/suspend-to-ram-time \
  2> /dev/null || true

# - announces the event
/usr/bin/dbus-send --type=signal --system / \
  org.chromium.PowerManager.PowerStateChanged string:mem

# - stores the current power status
/usr/bin/devkit-power -d > /tmp/power-status-on-suspend

# - suspends the cryptohome device
#CRYPTOHOME=/dev/mapper/cryptohome
#/usr/bin/test -b $CRYPTOHOME && /sbin/dmsetup suspend $CRYPTOHOME

# - suspends to ram
echo -n mem > /sys/power/state

# On lid open:
# - has it such that you don't have to press a key to display lock screen
xscreensaver-command -deactivate

# - announces the event
/usr/bin/dbus-send --type=signal --system / \
  org.chromium.PowerManager.PowerStateChanged string:on &

# - sends UMA metrics on resume
/usr/bin/send_metrics_on_resume

# - resumes cryptohome device
#/usr/bin/test -b $CRYPTOHOME && /sbin/dmsetup resume $CRYPTOHOME
