#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

logger -t powerd_suspend "Going to suspend-to-RAM state"

# - logs the time going to suspend (no-op if no RTC).
cp /sys/class/rtc/rtc0/since_epoch /var/log/metrics/suspend-to-ram-time \
  2> /dev/null || true

# - announces the event
/usr/bin/dbus-send --type=signal --system / \
  org.chromium.PowerManager.PowerStateChanged string:mem

# - stores the current power status
power_status_on_suspend=/tmp/power-status-on-suspend
/usr/bin/devkit-power -d \
  | /bin/grep -Eq '^[[:space:]]+online:[[:space:]]+no$'
if [ $? -eq 0 ]; then
    echo OnBattery > $power_status_on_suspend
else
    echo OnAC > $power_status_on_suspend
    # - enables autosuspend for USB devices. This shaves about 300ms
    #   from resume time.
    for i in /sys/bus/usb/devices/*/power/level; do echo auto > $i; done
fi

# - deletes hwclock snapshot from previous resumes
rm -f /tmp/hwclock-on-resume

# - suspends the cryptohome device
#CRYPTOHOME=/dev/mapper/cryptohome
#/usr/bin/test -b $CRYPTOHOME && /sbin/dmsetup suspend $CRYPTOHOME

# - suspends to ram
echo -n mem > /sys/power/state

# On resume:
# - records the hwclock time at resume
/sbin/hwclock --utc --debug > /tmp/hwclock-on-resume &

# - announces the event
/usr/bin/dbus-send --type=signal --system / \
  org.chromium.PowerManager.PowerStateChanged string:on &

# - sends UMA metrics on resume
/usr/bin/send_metrics_on_resume &

#  - re-kicks laptop mode since AC<->Battery transition might've happened
#    while the system was suspended. Sleep a bit, though, to take care of
#    racing with USB stack coming up.
sleep 10 && /usr/sbin/laptop_mode force &

# - resumes cryptohome device
#/usr/bin/test -b $CRYPTOHOME && /sbin/dmsetup resume $CRYPTOHOME
