#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Don't lock if no one is logged in.
[ -f /var/run/state/logged-in ] || exit 0

logger -t powerd_lock_screen "Locking screen"
/usr/bin/dbus-send --type=method_call --system  \
  --dest=org.chromium.PowerManager /org/chromium/PowerManager \
  org.chromium.PowerManager.RequestLockScreen
