/* Generated by dbus-binding-tool; do not edit! */

#include <glib/gtypes.h>
#include <glib/gerror.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_ImageBurnerInterface
#define DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_ImageBurnerInterface

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_chromium_ImageBurnerInterface_burn_image (DBusGProxy *proxy, const char * IN_from_path, const char * IN_to_path, GError **error)

{
  return dbus_g_proxy_call (proxy, "BurnImage", error, G_TYPE_STRING, IN_from_path, G_TYPE_STRING, IN_to_path, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*org_chromium_ImageBurnerInterface_burn_image_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
org_chromium_ImageBurnerInterface_burn_image_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(org_chromium_ImageBurnerInterface_burn_image_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_chromium_ImageBurnerInterface_burn_image_async (DBusGProxy *proxy, const char * IN_from_path, const char * IN_to_path, org_chromium_ImageBurnerInterface_burn_image_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "BurnImage", org_chromium_ImageBurnerInterface_burn_image_async_callback, stuff, g_free, G_TYPE_STRING, IN_from_path, G_TYPE_STRING, IN_to_path, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_ImageBurnerInterface */

G_END_DECLS
