#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.


BACKLIGHTPATH="/sys/class/backlight"

for INTERFACE in ${BACKLIGHTPATH}/* ; do
  BRIGHTNESS="${INTERFACE}/brightness"
  MAX_BRIGHTNESS="${INTERFACE}/max_brightness"
  [ -f "${BRIGHTNESS}" -a -f "${MAX_BRIGHTNESS}" ] || continue
  cp -f "${MAX_BRIGHTNESS}" "${BRIGHTNESS}"
done

exit 0
