#!/bin/sh
# Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
# rsyslogd is somewhat stupid and can only supply a single argument to the
# log-rotation program, so we have this handy little wrapper around mv(1).
mv "$1" "$1.1"
