#!/bin/sh -e
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

dump_var_log() {
  local filename="$1"
  local size="$2"

  echo "################################"
  echo "### ${filename}"
  echo "################################"
  tail -c "${size}" "/var/log/${filename}" || echo "No ${filename}"
}

dump_var_log arc.log 400k

if [ -d /var/log/android ] ; then
  # Dump only the last 3 log files.
  for f in `ls -1tr /var/log/android | tail -3` ; do
    dump_var_log "android/${f}" 30k
  done
fi

# TODO(hidehiko): Remove these in M72.
rm -f /var/log/android.kmsg
rm -f /var/log/arc-boot-continue.log
rm -f /var/log/arc-lifetime.log
rm -f /var/log/arc-network.log
rm -f /var/log/arc-removable-media.log
rm -f /var/log/arc-sensor.log
rm -f /var/log/arc-start-sysctl.log
rm -f /var/log/arc-stop-sysctl.log
rm -f /var/log/arc-system-mount.log
rm -f /var/log/arc-ureadahead.log
rm -f /var/log/arc-ureadahead-trace.log
