#!/bin/sh -e
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

dump_var_log() {
  local filename="$1"

  echo "################################"
  echo "### ${filename}"
  echo "################################"
  tail -c 30k "/var/log/${filename}" || echo "No ${filename}"
}

dump_var_log arc.log

# TODO(hidehiko): Move these logs into arc.log.
dump_var_log android.kmsg
dump_var_log arc-camera.log
dump_var_log arc-removable-media.log
dump_var_log arc-sensor.log
dump_var_log arc-start-sysctl.log
dump_var_log arc-stop-sysctl.log
dump_var_log arc-system-mount.log
dump_var_log arc-ureadahead-trace.log
dump_var_log arc-ureadahead.log

# TODO(hidehiko): Remove these in M71.
rm -f /var/log/arc-adbd.log
rm -f /var/log/arc-obb-mounter.log
rm -f /var/log/arc-sdcard.log
rm -f /var/log/arc-setfattr.log
rm -f /var/log/arc-stale-directory-remover.log

# TODO(hidehiko): Remove these in M72.
rm -f /var/log/arc-boot-continue.log
rm -f /var/log/arc-lifetime.log
rm -f /var/log/arc-network.log

if [ -d /var/log/android ] ; then
  # Dump only the last 3 log files.
  for f in `ls -1tr /var/log/android | tail -3` ; do
    dump_var_log android/$f
  done
fi
