#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

tail -c 512k /var/log/arc.log || echo "No /var/log/arc.log"

# TODO(hidehiko): Remove these in M72.
rm -f /var/log/android.kmsg
rm -f /var/log/arc-boot-continue.log
rm -f /var/log/arc-lifetime.log
rm -f /var/log/arc-network.log
rm -f /var/log/arc-removable-media.log
rm -f /var/log/arc-sensor.log
rm -f /var/log/arc-start-sysctl.log
rm -f /var/log/arc-stop-sysctl.log
rm -f /var/log/arc-system-mount.log
rm -f /var/log/arc-ureadahead.log
rm -f /var/log/arc-ureadahead-trace.log

# TODO(hidehiko): Remove these in M73.
rm -rf /var/log/android
