#!/bin/sh
echo "cras-config-dir: $(cros_config --abspath /audio/main cras-config-dir)"
echo "ucm-suffix: $(cros_config /audio/main ucm-suffix)"
echo "arc product: $(cros_config /arc/build-properties product)"
echo "arc oem: $(cros_config /arc/build-properties oem)"
echo "arc device: $(cros_config /arc/build-properties device)"
echo "arc marketing-name: $(cros_config /arc/build-properties marketing-name)"
echo "arc metrics-tag: $(cros_config /arc/build-properties metrics-tag)"
echo "power charging-ports: $(cros_config /power charging-ports)"
echo "power keyboard-backlight-no-als-brightness: $(cros_config /power keyboard-backlight-no-als-brightness)"
echo "power low-battery-shutdown-percent: $(cros_config /power low-battery-shutdown-percent)"
echo "power power-supply-full-factor: $(cros_config /power power-supply-full-factor)"
echo "power set-wifi-transmit-power-for-tablet-mode: $(cros_config /power set-wifi-transmit-power-for-tablet-mode)"
echo "power suspend-to-idle: $(cros_config /power suspend-to-idle)"
echo "brand-code: $(cros_config / brand-code)"
echo "touch present: $(cros_config /touch present)"
echo "touch probe-regex: $(cros_config /touch probe-regex)"
echo "wallpaper: $(cros_config / wallpaper)"
echo "powerd-prefs: $(cros_config / powerd-prefs)"
echo "test-label: $(cros_config / test-label)"
