#!/bin/sh
echo -e "cras-config-dir: $(cros_config --abspath /audio/main cras-config-dir)\n"
echo -e "ucm-suffix: $(cros_config /audio/main ucm-suffix)\n"
echo -e "arc product: $(cros_config /arc/build-properties product)\n"
echo -e "arc oem: $(cros_config /arc/build-properties oem)\n"
echo -e "arc device: $(cros_config /arc/build-properties device)\n"
echo -e "arc marketing-name: $(cros_config /arc/build-properties marketing-name)\n"
echo -e "arc metrics-tag: $(cros_config /arc/build-properties metrics-tag)\n"
echo -e "power charging-ports: $(cros_config /power charging-ports)\n"
echo -e "power keyboard-backlight-no-als-brightness: $(cros_config /power keyboard-backlight-no-als-brightness)\n"
echo -e "power low-battery-shutdown-percent: $(cros_config /power low-battery-shutdown-percent)\n"
echo -e "power power-supply-full-factor: $(cros_config /power power-supply-full-factor)\n"
echo -e "power set-wifi-transmit-power-for-tablet-mode: $(cros_config /power set-wifi-transmit-power-for-tablet-mode)\n"
echo -e "power suspend-to-idle: $(cros_config /power suspend-to-idle)\n"
echo -e "brand-code: $(cros_config / brand-code)\n"
echo -e "touch present: $(cros_config /touch present)\n"
echo -e "touch probe-regex: $(cros_config /touch probe-regex)\n"
echo -e "wallpaper: $(cros_config / wallpaper)\n"
echo -e "powerd-prefs: $(cros_config / powerd-prefs)\n"
echo -e "test-label: $(cros_config / test-label)\n"
