/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef CAMERA_HAL_MEDIATEK_MTKCAM_UTILS_TUNINGUTILS_EISPPROFILE_STRING_H_
#define CAMERA_HAL_MEDIATEK_MTKCAM_UTILS_TUNINGUTILS_EISPPROFILE_STRING_H_

static const char* const strEIspProfile[] = {
    "Preview",
    "Video",
    "Capture",
    "iHDR_Preview",
    "zHDR_Preview",
    "mHDR_Preview",
    "iHDR_Video",
    "zHDR_Video",
    "mHDR_Video",
    "iHDR_Preview_VSS",
    "zHDR_Preview_VSS",
    "mHDR_Preview_VSS",
    "iHDR_Video_VSS",
    "zHDR_Video_VSS",
    "mHDR_Video_VSS",
    "zHDR_Capture",
    "mHDR_Capture",
    "Auto_iHDR_Preview",
    "Auto_zHDR_Preview",
    "Auto_mHDR_Preview",
    "Auto_iHDR_Video",
    "Auto_zHDR_Video",
    "Auto_mHDR_Video",
    "Auto_iHDR_Preview_VSS",
    "Auto_zHDR_Preview_VSS",
    "Auto_mHDR_Preview_VSS",
    "Auto_iHDR_Video_VSS",
    "Auto_zHDR_Video_VSS",
    "Auto_mHDR_Video_VSS",
    "Auto_zHDR_Capture",
    "Auto_mHDR_Capture",
    "MFNR_Before_Blend",
    "MFNR_Single",
    "MFNR_MFB",
    "MFNR_After_Blend",
    "zHDR_Capture_MFNR_Before_Blend",
    "zHDR_Capture_MFNR_Single",
    "zHDR_Capture_MFNR_MFB",
    "zHDR_Capture_MFNR_After_Blend",
    "EIS_Preview",
    "EIS_Video",
    "EIS_iHDR_Preview",
    "EIS_zHDR_Preview",
    "EIS_mHDR_Preview",
    "EIS_iHDR_Video",
    "EIS_zHDR_Video",
    "EIS_mHDR_Video",
    "EIS_Auto_iHDR_Preview",
    "EIS_Auto_zHDR_Preview",
    "EIS_Auto_mHDR_Preview",
    "EIS_Auto_iHDR_Video",
    "EIS_Auto_zHDR_Video",
    "EIS_Auto_mHDR_Video",
    "Capture_MultiPass_HWNR",
    "YUV_Reprocess",
    "Flash_Capture",
    "Preview_Capture_ZOOM1",
    "Preview_Capture_ZOOM2",
    "Video_Preview_ZOOM1",
    "Video_Preview_ZOOM2",
    "Video_Video_ZOOM1",
    "Video_Video_ZOOM2",
    "Capture_Capture_ZOOM1",
    "Capture_Capture_ZOOM2",
    "MFNR_Before_ZOOM1",
    "MFNR_Before_ZOOM2",
    "MFNR_Single_ZOOM1",
    "MFNR_Single_ZOOM2",
    "MFNR_MFB_ZOOM1",
    "MFNR_MFB_ZOOM2",
    "MFNR_After_ZOOM1",
    "MFNR_After_ZOOM2",
    "Flash_Capture_ZOOM1",
    "Flash_Capture_ZOOM2",
    "N3D_Preview",
    "N3D_Video",
    "N3D_Capture",
    "N3D_Denoise",
    "N3D_Preview_toW",
    "N3D_Video_toW",
    "N3D_Capture_toW",
    "N3D_Denoise_toGGM",
    "N3D_Denoise_toYUV",
    "N3D_Denoise_toW",
    "N3D_MFHR_Before_Blend",
    "N3D_MFHR_Single",
    "N3D_MFHR_MFB",
    "N3D_MFHR_After_Blend",
    "SWHDR_Phase1",
    "SWHDR_Phase2",
    "MFNR_Before_ZOOM0",
    "MFNR_Single_ZOOM0",
    "MFNR_MFB_ZOOM0",
    "MFNR_After_ZOOM0",
    "Preview_Preview_ZOOM1",
    "Preview_Preview_ZOOM2",
    "Preview_Video_ZOOM1",
    "Preview_Video_ZOOM2",
    "zHDR_Flash_Capture",
    "mHDR_Flash_Capture",
    "Auto_zHDR_Flash_Capture",
    "Auto_mHDR_Flash_Capture",
    "NUM",
};

#endif  // CAMERA_HAL_MEDIATEK_MTKCAM_UTILS_TUNINGUTILS_EISPPROFILE_STRING_H_
