@startuml

!include template.plantuml

package "chrome os user land" as chromeos {
    object "BlueZ" as bluez
}

package "Linux Kernel 3.8" as kernel8 {
}

package "Linux Kernel 3.10" as kernel7 {
}

package "Linux Kernel 3.14" as kernel6 {
}

package "Linux Kernel 3.18" as kernel5 {
}

package "Linux Kernel 4.4" as kernel4 {
}

package "Linux Kernel 4.14" as kernel3 {
}

package "Linux Kernel 4.19" as kernel2 {
}

package "Linux Kernel 5.4" as kernel1 {
}

package "Linux Kernel .Next" as kernelnext {
}

chromeos -down-> kernel8
chromeos -down-> kernel7
chromeos -down-> kernel6
chromeos -down-> kernel5
chromeos -down-> kernel4
chromeos -down-> kernel3
chromeos -down-> kernel2
chromeos -down-> kernel1
chromeos -down.-> kernelnext

@enduml