@startuml

/' This diagram skin template loosely matches the Bluetooth SIG designs. '/

skinparam {
    RoundCorner 10
    Monochrome true
    ParticipantBackgroundColor white
    NoteTextAlignment center
    SequenceMessageAlignment center
}
hide footbox

@enduml