#! /bin/sh
# Copyright 2017 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

for path in /sys/bus/iio/devices/iio:device*/*calibbias; do
  printf '%s: ' "${path}"
  cat "${path}"
done
