#! /bin/sh

# Copyright (c) 2014 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# This script provides various data about the internal disk to show on the
# chrome://system page. It will run once on startup to dump output to the file
# /var/log/storage_info.txt which will be read later by debugd when the user
# opens the chrome://system page.
. /usr/share/misc/storage-info-common.sh

: ${STORAGE_INFO_FILE:="/var/log/storage_info.txt"}

rm -f "${STORAGE_INFO_FILE}"
touch "${STORAGE_INFO_FILE}"
chmod 644 "${STORAGE_INFO_FILE}"

get_storage_info > "${STORAGE_INFO_FILE}"
