#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Simple script meant to gather basic system data and serve as an example
# of a system log script for userfeedback

CLIENTID_FILE=/home/chronos/Consent\ To\ Send\ Stats
echo "LOGDATE="`date`
cat /etc/lsb-release
echo "hostname="`hostname`
echo "uname="`uname -a`
echo "cpu="`uname -p`
echo "hw_platform="`uname -i`
if [ -f "${CLIENTID_FILE}" ]; then
  echo ClientID=`cat "${CLIENTID_FILE}"`
fi