#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Simple script meant to gather basic system data and serve as an example
# of a system log script for userfeedback

echo "LOGDATE="`date`
cat /etc/lsb-release
echo "hostname="`hostname`
echo -n "/var/log/fontconfig.log"='"""'
cat /var/log/fontconfig.log
echo '"""'
echo "uname="`uname`
