#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Script to read commands from ../etc/sys_log_utils.lst and execute
# them, creating a key/value pair as output, with the key=command and
# value=output of the command.

set -e

if [ -f "${1}" ]
then
  log_utils_file=${1}
else
  log_utils_file="$(dirname "$0")/../etc/sys_log_utils.lst"
fi

# Do not exit in case a script wasn't found or threw an error.
for i in `cat ${log_utils_file}`
do
  log=`${i} 2>/dev/null` && echo "${i}"='"""'"${log}"'"""'
done

