#!/bin/bash
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This is a fake mosys used during tests

if [[ $# -ne 2 ]]; then
  exit 1
fi

if [[ "$1" != "platform" ]]; then
  exit 1
fi

case "$2" in
  model )
    echo test_mosys_model_string
    ;;
  brand )
    echo BRND
    ;;
  * )
    exit 1
    ;;
esac
