#!/bin/sh

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Shutdown is best-effort. We don't want to die on errors.
set +e

# Remount root in case a developer has remounted it rw for some reason.
mount -n -o remount,ro /

# Lazy umount the tmpfs dirs under /var so we can immediately umount it.
umount -n -l /var/run /var/lock
if [ -e /dev/mapper/encstateful ]; then
  mount-encrypted umount >/tmp/umount-encrypted.log 2>&1
  if [ $? -ne 0 ] ; then
    mv /tmp/umount-encrypted.log /mnt/stateful_partition/
  fi
  umount -n /usr/local /home /mnt/stateful_partition
  rc=$?
else
  umount -n /var /usr/local /home /mnt/stateful_partition
  rc=$?
fi
if [ $rc -ne 0 ] ; then
  mount > /mnt/stateful_partition/shutdown_stateful_umount_failure
fi

# Just in case something didn't unmount properly above.
sync

# Ensure that we always claim success.
exit 0
