#!/bin/sh
# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

IMAGELOADER_DIR="/var/lib/imageloader"
if [ -L "${IMAGELOADER_DIR}" -o ! -d "${IMAGELOADER_DIR}" ]; then
  rm -rf "${IMAGELOADER_DIR}"
  mkdir -m=0755 "${IMAGELOADER_DIR}"
  chown imageloaderd:imageloaderd "${IMAGELOADER_DIR}"
fi

/usr/sbin/imageloader "${@}"
