#!/bin/sh

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This command is deprecated in favor of the implementation in /usr/bin/modem
/usr/bin/modem set-carrier "$@"
