// Copyright 2019 The Chromium OS Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef VM_TOOLS_CICERONE_MOCK_TREMPLIN_STUB_H_
#define VM_TOOLS_CICERONE_MOCK_TREMPLIN_STUB_H_

// For unclear reasons, this autogenerated file doesn't come with header
// guards. Therefore, every file that wants to include it must do so via this
// header, which does.
#include "tremplin_mock.grpc.pb.h"  // NOLINT(build/include)

#endif  // VM_TOOLS_CICERONE_MOCK_TREMPLIN_STUB_H_
