/*
 * Copyright (C) 2019 MediaTek Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef CAMERA_HAL_MEDIATEK_MTKCAM_DRV_SENSOR_CUSTOM_CONFIG_IMGSENSOR_CONFIG_STATIC_METADATA_1_COMMON_RAW_H_
#define CAMERA_HAL_MEDIATEK_MTKCAM_DRV_SENSOR_CUSTOM_CONFIG_IMGSENSOR_CONFIG_STATIC_METADATA_1_COMMON_RAW_H_

STATIC_METADATA_BEGIN(1, COMMON_RAW)
//------------------------------------------------------------------------------
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_MAX_REGIONS)
CONFIG_ENTRY_VALUE(1, MINT32);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_SENSITIVITY_RANGE)
CONFIG_ENTRY_VALUE(100, MINT32);
CONFIG_ENTRY_VALUE(200, MINT32);
CONFIG_ENTRY_VALUE(400, MINT32);
CONFIG_ENTRY_VALUE(800, MINT32);
CONFIG_ENTRY_VALUE(1600, MINT32);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_EXPOSURE_TIME_RANGE)
CONFIG_ENTRY_VALUE(1000L, MINT64);         //  1 us
CONFIG_ENTRY_VALUE(30000000000L, MINT64);  // 30 sec
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_SENSOR_INFO_MAX_FRAME_DURATION)
CONFIG_ENTRY_VALUE(30000000000L, MINT64);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_ANTIBANDING_MODES)
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_50HZ, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_60HZ, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_ANTIBANDING_MODE_AUTO, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_MODES)
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_AUTO_FLASH, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_ALWAYS_FLASH, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_AVAILABLE_TARGET_FPS_RANGES)
CONFIG_ENTRY_VALUE(5, MINT32);
CONFIG_ENTRY_VALUE(30, MINT32);
CONFIG_ENTRY_VALUE(15, MINT32);
CONFIG_ENTRY_VALUE(15, MINT32);
CONFIG_ENTRY_VALUE(30, MINT32);
CONFIG_ENTRY_VALUE(30, MINT32);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_COMPENSATION_RANGE)
CONFIG_ENTRY_VALUE(-3, MINT32);
CONFIG_ENTRY_VALUE(+3, MINT32);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AE_COMPENSATION_STEP)
CONFIG_ENTRY_VALUE(MRational(1, 1), MRational);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AF_AVAILABLE_MODES)
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_AUTO, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_MACRO, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_CONTINUOUS_VIDEO, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_CONTINUOUS_PICTURE, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AWB_AVAILABLE_MODES)
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_AUTO, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_INCANDESCENT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_FLUORESCENT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_WARM_FLUORESCENT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_DAYLIGHT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_CLOUDY_DAYLIGHT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_TWILIGHT, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_SHADE, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AVAILABLE_EFFECTS)
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_MONO, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_NEGATIVE, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_SEPIA, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_WHITEBOARD, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_BLACKBOARD, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_EFFECT_MODE_AQUA, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_AVAILABLE_SCENE_MODES)
CONFIG_ENTRY_VALUE(MTK_CONTROL_SCENE_MODE_UNSUPPORTED, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
CONFIG_METADATA_BEGIN(MTK_CONTROL_SCENE_MODE_OVERRIDES)
//  MTK_CONTROL_SCENE_MODE_UNSUPPORTED
CONFIG_ENTRY_VALUE(MTK_CONTROL_AE_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AWB_MODE_OFF, MUINT8);
CONFIG_ENTRY_VALUE(MTK_CONTROL_AF_MODE_OFF, MUINT8);
CONFIG_METADATA_END()
//==========================================================================
//------------------------------------------------------------------------------
STATIC_METADATA_END()

#endif  // CAMERA_HAL_MEDIATEK_MTKCAM_DRV_SENSOR_CUSTOM_CONFIG_IMGSENSOR_CONFIG_STATIC_METADATA_1_COMMON_RAW_H_
