#!/bin/dash
# Copyright (c) 2009-2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Chrosh commands that are only loaded when we're booting from removable
# media.

if [ "$(basename $0)" = "crosh-usb" ]; then
  exec "$(dirname $0)/crosh --usb"
fi

USB_HELP='
 install [<dev>]
  Install ChromeOS to the target device, clearing out all existing data.

 upgrade [<dev>]
  Upgrade an existing ChromeOS installation, saving existing user data.

 update_firmware
  Update system firmware, if applicable.
'

HELP="$HELP$USB_HELP"

do_install() {
  if [ "$1" ]; then
    if [ $(expr "$1" : '^/dev/[[:alnum:]]\+$') == 0 ]; then
      echo "Invalid device name: $1"
      return 1
    fi

    local dst="$1"
    shift

    $CHROMEOS_INSTALL --dst="$dst" "$@"
  else
    $CHROMEOS_INSTALL "$@"
  fi
}

cmd_update_firmware() {
  local CHROMEOS_FIRMWARE_UPDATE="/usr/sbin/chromeos-firmwareupdate"

  if [ -s $CHROMEOS_FIRMWARE_UPDATE ]; then
    $CHROMEOS_FIRMWARE_UPDATE
  else
    echo "There is no firmware update in this Chrome OS image."
  fi
}

cmd_install() {
  do_install "$1"
}

cmd_upgrade() {
  do_install "$1" --preserve_stateful
}
