#!/bin/dash
# Copyright (c) 2009-2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# Chrosh commands that are only loaded when we're booting from removable
# media.

if [ "$(basename $0)" = "crosh-usb" ]; then
  exec "$(dirname $0)/crosh --usb"
fi

USB_HELP='
 install [<dev>]
  Install ChromeOS to the target device.
'

HELP="$HELP$USB_HELP"

cmd_install() {
  if [ "$1" ]; then
    if [ $(expr "$1" : '^/dev/[[:alnum:]]\+$') == 0 ]; then
      echo "Invalid device name: $1"
      return 1
    fi

    $CHROMEOS_INSTALL --dst="$1"
  else
    $CHROMEOS_INSTALL
  fi
}
