#!/bin/sh

# Copyright (c) 2012 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# This file is meant for debugging use to manually trigger a proper
# suspend excercising the full path through the power manager.
# The actual work to suspend the system is done by powerd_suspend.

dbus-send --type=signal --system \
  /org/chromium/PowerManager org.chromium.PowerManager.RequestSuspend
