/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef _DBUS_GLIB_ASYNC_DATA_FREE
#define _DBUS_GLIB_ASYNC_DATA_FREE
static
#ifdef G_HAVE_INLINE
inline
#endif
void
_dbus_glib_async_data_free (gpointer stuff)
{
	g_slice_free (DBusGAsyncData, stuff);
}
#endif

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_SessionManagerInterface
#define DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_SessionManagerInterface

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_chromium_SessionManagerInterface_emit_login_prompt_ready (DBusGProxy *proxy, gboolean* OUT_emitted, GError **error)

{
  return dbus_g_proxy_call (proxy, "EmitLoginPromptReady", error, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_emitted, G_TYPE_INVALID);
}

typedef void (*org_chromium_SessionManagerInterface_emit_login_prompt_ready_reply) (DBusGProxy *proxy, gboolean OUT_emitted, GError *error, gpointer userdata);

static void
org_chromium_SessionManagerInterface_emit_login_prompt_ready_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_emitted;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_emitted, G_TYPE_INVALID);
  (*(org_chromium_SessionManagerInterface_emit_login_prompt_ready_reply)data->cb) (proxy, OUT_emitted, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_chromium_SessionManagerInterface_emit_login_prompt_ready_async (DBusGProxy *proxy, org_chromium_SessionManagerInterface_emit_login_prompt_ready_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "EmitLoginPromptReady", org_chromium_SessionManagerInterface_emit_login_prompt_ready_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_chromium_SessionManagerInterface_start_session (DBusGProxy *proxy, const char * IN_email_address, const char * IN_unique_identifier, gboolean* OUT_done, GError **error)

{
  return dbus_g_proxy_call (proxy, "StartSession", error, G_TYPE_STRING, IN_email_address, G_TYPE_STRING, IN_unique_identifier, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_done, G_TYPE_INVALID);
}

typedef void (*org_chromium_SessionManagerInterface_start_session_reply) (DBusGProxy *proxy, gboolean OUT_done, GError *error, gpointer userdata);

static void
org_chromium_SessionManagerInterface_start_session_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_done;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_done, G_TYPE_INVALID);
  (*(org_chromium_SessionManagerInterface_start_session_reply)data->cb) (proxy, OUT_done, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_chromium_SessionManagerInterface_start_session_async (DBusGProxy *proxy, const char * IN_email_address, const char * IN_unique_identifier, org_chromium_SessionManagerInterface_start_session_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "StartSession", org_chromium_SessionManagerInterface_start_session_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_email_address, G_TYPE_STRING, IN_unique_identifier, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
org_chromium_SessionManagerInterface_stop_session (DBusGProxy *proxy, const char * IN_unique_identifier, gboolean* OUT_done, GError **error)

{
  return dbus_g_proxy_call (proxy, "StopSession", error, G_TYPE_STRING, IN_unique_identifier, G_TYPE_INVALID, G_TYPE_BOOLEAN, OUT_done, G_TYPE_INVALID);
}

typedef void (*org_chromium_SessionManagerInterface_stop_session_reply) (DBusGProxy *proxy, gboolean OUT_done, GError *error, gpointer userdata);

static void
org_chromium_SessionManagerInterface_stop_session_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gboolean OUT_done;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_BOOLEAN, &OUT_done, G_TYPE_INVALID);
  (*(org_chromium_SessionManagerInterface_stop_session_reply)data->cb) (proxy, OUT_done, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
org_chromium_SessionManagerInterface_stop_session_async (DBusGProxy *proxy, const char * IN_unique_identifier, org_chromium_SessionManagerInterface_stop_session_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_slice_new (DBusGAsyncData);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "StopSession", org_chromium_SessionManagerInterface_stop_session_async_callback, stuff, _dbus_glib_async_data_free, G_TYPE_STRING, IN_unique_identifier, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_org_chromium_SessionManagerInterface */

G_END_DECLS
