#!/usr/bin/python

import sys
import dbus, flimflam

if (len(sys.argv) < 3):
    print "Usage: %s <device | interface> <type>" % (sys.argv[0])
    sys.exit(1)

(_, name, ipconfig) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())

device = flim.FindElementByNameSubstring('Device', name)
if device is None:
    device = flim.FindElementByPropertySubstring('Device', 'Interface', name)

device.AddIPConfig(ipconfig)
