#!/usr/bin/python

import pprint, sys
import dbus, flimflam

if (len(sys.argv) < 2):
    print "Usage: %s <ssid> [passphrase] [security]" % (sys.argv[0])
    sys.exit(1)

print "Attempting to connect service %s" % (sys.argv[1])

flim = flimflam.FlimFlam(dbus.SystemBus())

params = {}
params["mode"] = "managed"
params["ssid"] = sys.argv[1]
if len(sys.argv) > 2:
    if len(sys.argv) > 3:
        params["security"] = sys.argv[3]
    else:
        params["security"] = "psk"
    params["passphrase"] = sys.argv[2]
else:
    params["security"] = "none"
    params["passphrase"] = ""

(success, diagnostics) = flim.ConnectService(service_type='wifi',
                                             **params)

print 'Success:', success
pprint.pprint(diagnostics)
