#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) < 2):
    print "Profile pathname required"
    sys.exit(1)

flim = flimflam.FlimFlam(dbus.SystemBus())
profile = flim.CreateProfile(sys.argv[1])
print "New profile created at %s" % (profile.object_path)
