#!/usr/bin/python

import dbus, flimflam

flim = flimflam.FlimFlam(dbus.SystemBus())

active = flim.GetActiveProfile()

for profile in flim.GetObjectList("Profile"):
    if profile.object_path == active.object_path:
        print "[ %s ]  <== active" % (profile.object_path)
    else:
        print "[ %s ]" % (profile.object_path)

    properties = profile.GetProperties(utf8_strings = True)
    for key in properties.keys():
        print "    %s = %s" % \
            (key, flimflam.convert_dbus_value(properties[key], 4))

    print
