#!/usr/bin/python

import dbus, flimflam

flim = flimflam.FlimFlam(dbus.SystemBus())

active = flim.GetActiveProfile()

for profile in flim.GetObjectList("Profile"):
    if profile.object_path == active.object_path:
        print "[ %s ]  <== active" % (profile.object_path)
    else:
        print "[ %s ]" % (profile.object_path)

    properties = profile.GetProperties(utf8_strings = True)
    if not "Entries" in properties:
        continue
    for ident in properties["Entries"]:
        entry = profile.GetEntry(ident)
        print "    [%s] = %s" % (ident, flimflam.convert_dbus_value(entry, 4))
