#!/usr/bin/python

# Copyright (c) 2011 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import mm

devices = mm.EnumerateDevices()

for manager, path in devices:
    print path

    modem = manager.Modem(path)

    modem.Enable(False)
