#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) > 2):
    print "usage: %s [identifier]" % sys.argv[0]
    sys.exit(1)

flim = flimflam.FlimFlam(dbus.SystemBus())
if (len(sys.argv) == 2):
    flim.PopProfile(sys.argv[1])
else:
    flim.PopAnyProfile()
