#!/usr/bin/python

import dbus, flimflam, sys

if (len(sys.argv) < 4):
    print "Usage: %s <path> <key> <value>" % (sys.argv[0])
    sys.exit(1)

(_, path, key, value) = sys.argv

flim = flimflam.FlimFlam(dbus.SystemBus())

ipconfig = flim.GetObjectInterface("IPConfig", path)
if key == "Prefixlen":
    ipconfig.SetProperty(key, int(value))
elif key == "Mtu":
    ipconfig.SetProperty(key, int(value))
else:
    ipconfig.SetProperty(key, value)
