#!/bin/sh

# Copyright 2016 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e

# As of Chrome OS 58, we dump VPD information unconditionally, so it is always
# available on the login screen, even after OOBE (see crbug.com/216422). Note
# that the machine-info.conf upstart config file takes care of deleting the
# $MACHINE_INFO file before a user session starts.
touch "${MACHINE_INFO}"
chmod 0644 "${MACHINE_INFO}"
if crossystem "mainfw_type?nonchrome"; then
  echo "serial_number=\"nonchrome-$(date -u +%s)\""
else
  # Dump full information in the VPD, including the serial number.
  dump_vpd_log --full --stdout
  # Dynamic information.
  echo "customization_id=\"$(mosys platform customization)\""
  echo "rlz_brand_code=\"$(mosys platform brand)\""
fi >> "${MACHINE_INFO}"
