#!/bin/sh -u
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# A script to securely remove data off the stateful partition, ignoring any
# symlinks it encounters.

SAFE_REMOVE_PATHS="/mnt/stateful_partition/unencrypted/oobe_auto_config"

for path in "${SAFE_REMOVE_PATHS}"; do
  # If the path exists and is a symlink, then it should be ignored.
  if [ -e "${path}" -a ! -L "${path}" ]; then
    # Recursively delete all files in the path. Note that we do not follow or
    # consider any symlinks.
    find "${path}" -type f -exec secure_erase_file {} \;

    # Delete the path, since its contents have already been destroyed.
    rm -rf "${path}"
  fi
done
